### ISSUE TITLE
Money drop

### ISSUE THREAD

**Issue by HolySSSS** [TFlippy/kag_territorycontrol#142]
Neutrals lose all coins that are vital to continue fighting
1 small genocide from a faction renders all neutrals useless
and encores the faction

this is the best fun-decreasing update to TC

**Comment by Vam-Jam** [comment]
incorrect, they drop 50% on death, this will be revisited in a future update

**Comment by HolySSSS** [comment]
losing half of the coins does feel a lot, getting killed 2+ times (especially in spawnkilling) makes you weaker to the faction

comparisons of %: 
50% - 25000 - 12500 - 6250 ; 10000 - 5000 - 2500 
30% - 25000 - 17500 - 12250 ; 10000 - 7000 - 4900 
25% - 25000 - 18750 - 14063 ; 10000 - 7500 - 5625
20% - 25000 - 20000 - 16000 ; 10000 - 8000 - 6400
hope this gets decreased to 30%

**Comment by jammer312** [comment]
How about going the other direction and making everyone (factionmen included) drop 100% coins on death?
It's still a step towards equalizing neutrals and factions (since ppl are complaining factions are too strong atm). And it'll finally introduce second real use case for bying gold (first one is when you hit coin cap but still want to hoard coins).

**Comment by laikadoggirl** [comment]
another spectacular idea from jammer, let see if everyone disagrees and vamist merges it anyway

**Comment by HolySSSS** [comment]
Thanks to Vamist for closing this issue!
