### ISSUE TITLE
Heavy weaponry ideas

### ISSUE THREAD

**Issue by HolySSSS** [TFlippy/kag_territorycontrol#143]
this is all just ideas, any suggestions, corrections or new ideas are welcome

Artillery:
Bertha, rate of fire is very low, 1 round 6 seconds, practically targets half the map, powerful
Old cannon, stuff anything into it and it will launch it horizontally (advanced catapult?)

Vehicles:
fighter, aka armored spotter
armored speedcar. just rams things a bit slower, driver doesn't take damage
kamikazi/bomb drone, a cheaper version of a cruise missile and a better version of rocket of doom

Explosives:
cluster-grenade or actual fragmentation grenade (SHARDS!)
bouncy explosives like banana would be funny 
drug-related bombs except pax/babby

**Comment by Gingerbeard5773** [comment]
Some of these ideas were already visited some months ago!

https://user-images.githubusercontent.com/68350259/113525520-aa3f0800-9572-11eb-8049-95387cb0d8b8.mp4

"Big Howitzer". I guess in your ideas you could combine the old cannon and this.

https://user-images.githubusercontent.com/68350259/113525631-2f2a2180-9573-11eb-806e-4c0671196320.mp4

I did shrapnel frag grenades at one point but I couldn't find the footage so I just redid it all.

I would have a third video of a "fighter plane" you described but I deleted all my footage.
Anyways, even though I have explored some of these ideas I never really finished them completely since they just didn't fit for TC imo. Though maybe shrapnel in the frag grenades makes sense.
