### ISSUE TITLE
Money headstart / Nextmap vote

### ISSUE THREAD

**Issue by HolySSSS** [TFlippy/kag_territorycontrol#151]
After successful nextmap vote people save part of their coins
and this creates imbalance between rounds

**Comment by HolySSSS** [comment]
misclicked submit, part 2

it's hard to nextmap when 1 faction gets 30% of the vote
it usually goes crazy

**Comment by laikadoggirl** [comment]
removing the money headstart is homo, literally just make map skip an even 50/50 vote instead of like 70%, and remove the gay neutral 50% coin loss

**Comment by Vam-Jam** [comment]
``literally just make map skip an even 50/50 vote instead of like 70%, `` This isnt a good idea. The vote % was increased because people would never let a game go above 30 mins

**Comment by laikadoggirl** [comment]
Ok but would you rather short games or games that never reset because a faction controls the map

**Comment by Vam-Jam** [comment]
> Ok but would you rather short games or games that never reset because a faction controls the map

The latter, short games do not work well in TC. People get angry that they can never progress far because a group of people decided to gang up and vote for next map

It went like this:
- Losing war? vote next map
- Dying too much? vote next map and it would probably go through
- Enemy team better then yours? vote next map

**Comment by HolySSSS** [comment]
> Ok but would you rather short games or games that never reset because a faction controls the map

This problem basically mentions issue #141 which is being fixed by Gingerbeard (Faction has 1 base - no contesting & can't travel to contested faction bases / mines). After adding his fix there are more chances to destroy/weaken the mentioned faction and then nextmap.

**Comment by laikadoggirl** [comment]
People get equally mad when a single faction murders the whole map by holding it hostage with the vote

**Comment by Vam-Jam** [comment]
> People get equally mad when a single faction murders the whole map by holding it hostage with the vote

Does not happen anywhere near as much as voting for next map did. Vote % will not be reduced to 50/50

**Comment by laikadoggirl** [comment]
cringe !

**Comment by Gingerbeard5773** [comment]
Reduce the vote % after 30 minutes of gametime otherwise keep the current percent. This seems like a simple issue to resolve?

**Comment by laikadoggirl** [comment]
not cringe !

**Comment by Gingerbeard5773** [comment]
when I mean reduce it would go from like 70% which is what it is like rn to maybe a 60% or 51% since having a 50/50 vote pass would cause anger

**Comment by jammer312** [comment]
Alternatively implement vote weight proportional to player age (how much time that player spent on server since last join).
Might want to implement some mechanism of ignoring rejoin disconnects (iirc non-staging kag lags like hell if you play TC for more than 20 minutes, and reconnecting helps, but such reconnect would kill the player age (without some mechanism to ignore that reconnect))

**Comment by HolySSSS** [comment]
> Reduce the vote % after 30 minutes of gametime otherwise keep the current percent. This seems like a simple issue to resolve?

This can help. Doesn't escape the mentality mentioned by Vam, but it's a good step.
Better yet: it reduces slowly 1% each 1 or 2 minutes to minimum 50% or 60%. 
1 minute: 70% - 30 minutes after the start of the game, start the reduce, 50% - 50 minutes, 60% - 40 minutes
2 minute: 70% - 30 minutes after the start of the game, start the reduce, 50% - 70 minutes, 60% - 50 minutes.

> Alternatively implement vote weight proportional to player age

Seems too complicated and hard to monitor. Is it worth the hussle?

**Comment by jammer312** [comment]
Or this
![image](https://user-images.githubusercontent.com/3525275/113750573-adbdc500-9713-11eb-8ebc-773172069919.png)

**Comment by laikadoggirl** [comment]
god jammer dont do that you scared me, I almost thought you were gonna dev again

**Comment by jammer312** [comment]
> Seems too complicated and hard to monitor. Is it worth the hussle?

I'd not say it's complicated, and it's easy to monitor as long as you log the voting process (and maybe player aging process too)

**Comment by HolySSSS** [comment]
To sum it up:

Leave it the same, wait for Ginger's fix
> Faction has 1 base - no contesting & can't travel to contested faction bases / mines

The required % for nextmap is decreased with time 
> 1 minute: 70% - 30 minutes after the start of the game, start the reduce, 50% - 50 minutes, 60% - 40 minutes
> 2 minute: 70% - 30 minutes after the start of the game, start the reduce, 50% - 70 minutes, 60% - 50 minutes.
> Casually drop 70% to 50% or 60% after 30 minutes.

Jammer's "Weight" idea
> Voting against have only 1 "weight", voting for have 0 to X "weight" (This vote "weight" slowly increases for each player, not for AFK ones though). X can be greater than 1 but it needs some tricky function probably. Though there's a problem with reconnects/crashes, the weight can drop in these cases.

**Comment by asperger-sind** [comment]
The Ginger's fix really seems strange because It just wouldn't work in a more skilled enviroment.

Oh hey pro gaymer1337 makes a faction base and then makes a second one
upgrades both and then has:
Upkeep, fast travel, extra storage, the ability to contest.

I say that it is too high of a power spike and is generally imbalanced considering that the new upkeep is just faction base spam, which gives you half the shit a faction needs.

The % over time solution looks like it's worth a try and I can agree that it can help.

Jammer's weight idea seems easily exploitable.
There are practically no players who just afk and wait until they can nextmap, they get a grudge and try to kill the person/faction they have a grudge on.

Basically they don't just afk, and that also gives the factions or who are controlling the server since minute 1 a large advantage since their cast doesn't change, and if it does then it's 1-2 players.

If a player joined the first second let's say with his friends, but the person doesn't control the server and wants to start a mapskip then the person and his friends will have a large vote advantage over let's say the faction that actually controls the server.

Blah blah blah I say that the "% over time solution" is hard to exploit, fixes some problems that need to be fixed and is generally simple.

**Comment by HolySSSS** [comment]
> Oh hey pro gaymer1337 makes a faction base and then makes a second one
> upgrades both and then has:
> Upkeep, fast travel, extra storage, the ability to contest.

> high of a power spike

Sadly the point wasn't straight enough. It's a power _hole_. If you have only _1 faction base_ at the moment, your last/first faction base can't be _contested_, so if your base is getting captured - you can respawn and fight back. When you get _2+ faction bases_, you can't respawn anymore at any of your faction bases that are currently in the capture process.

**Comment by HolySSSS** [comment]
Thanks to Vamist and Gingerbeard for closing this issue with: less coindrop, better contesting mechanics and allow chickens players spawn from the sky!
