### ISSUE TITLE
Peasants, stone and building/repairing stone walls.

### ISSUE THREAD

**Issue by jammer312** [TFlippy/kag_territorycontrol#6]
Balance builders and peasants please
For 125 coins you can get 250 stone
Peasant can spam stone faster than mega drill can break it (so as long as you have stone you can block the passage indefinitely) AND get 4 coins per 5 stone (one stone block placed), getting 200 coins for that spam. And that leads to stupid situations when peasant spawns at neutral spawn, runs to your base bying stone somewhere along the way, encases himself in stone and starts tunneling to break your camp or other buildings. Best drill in the game can't do anything against it as walls are repaired a lot faster than it breaks them, and so the only way to remove such rat is bombing your base or asking someone to flank it, which is surely a bit imbalanced (it takes two guys with high-tech equipment to drill out naked peasant with stone), and if you can't do it and just exhaust his stone reserves, he'll just respawn with almost double coins he had before such maneuer and just repeat it.
So, the solutions could be:
1. lower build rate of builders and peasants (might be better to lower build rate of peasants even further), which is kinda needed in vanilla, but noone will ever do it because reasons (rats want to play too)
2. lower coins yield per placed block, so getting more coins for placing material than is needed to buy it is impossible
3. make materials more expensive, so getting more coins for placing material than is needed to buy it is impossible (kinda like 2. but worse as it breaks economy if implemented without balancing other prices)
4. buff mega drills, idk, make them drill 2 tiles deep at once (instead of 1 tile deep) or do more damage to tiles

Might be applicable to other placeable blocks (wood blocks?), I didn't check it.

**Comment by TFlippy** [comment]
Peasants can't break iron / reinforced concrete / plasteel, so you can easily block them by reinforcing a wall with one of those.

If they still continue attacking, you can either surround your base with barbed wire or buy a zapper / sentry gun (which surely will slow them down and will force them to pick another way of attacking), or just slave them and put them into an iron box if they're too persistent.

1. I don't really want to slow down the pacing of the entire game by lowering the block placement speed due to few people ratting.

2. What I disliked about other gamemodes was that building wasn't rewarded accordingly and you had to make breaks to manually mine resources in order to continue building.

3. Same as 2.

4. I was thinking about speeding them up slightly and removing overheating for both types of drills, though not sure if that would help this problem.

**Comment by jammer312** [comment]
Placing lots of iron / reinforced concrete / plasteel requires having smeltery setup, which is nonexistant when you get raided in first minutes of the round. Barbed wire requires iron too irrc. Zapper/sentry are unobtainable unless you murder chickens and faction that rushed chickens and made reinforced base under their artillery, which still requires to abandon your base that is being ratted nonstop. And right now there's bug that allows slaves to suicide (see discord channel dedicated to ban requests, such thing happened yesterday), though it could be fixed (if it's not kag engine bug).
Meanwhile in suggestions channel ![](https://i.imgur.com/Ygw91Wn.png)

**Comment by jammer312** [comment]
I guess it's resolved
